services:
  postgres:
    image: postgres:16
    container_name: netshield-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: netshield_user
      POSTGRES_PASSWORD: netshield_pass
      POSTGRES_DB: netshield_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: netshield-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: